# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

import des

class Ui_MainWindow(object):

    mydes = des.des()

    def setupUi(self, MainWindow):
        font64 = QtGui.QFont()
        font64.setPointSize(10)
        font64.setKerning(True)
        font56 = QtGui.QFont()
        font56.setPointSize(10)
        font56.setKerning(True)
        font28 = QtGui.QFont()
        font28.setPointSize(11)
        font28.setKerning(True)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 642)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 940, 622))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 940, 1130))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.line_28 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_28.setGeometry(QtCore.QRect(660, 120, 20, 31))
        self.line_28.setStyleSheet("")
        self.line_28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setObjectName("line_28")
        self.line_54 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_54.setGeometry(QtCore.QRect(770, 540, 21, 21))
        self.line_54.setStyleSheet("")
        self.line_54.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_54.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_54.setObjectName("line_54")
        self.line_55 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_55.setGeometry(QtCore.QRect(850, 540, 21, 21))
        self.line_55.setStyleSheet("")
        self.line_55.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_55.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_55.setObjectName("line_55")
        self.line_24 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_24.setGeometry(QtCore.QRect(610, 460, 291, 21))
        self.line_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setObjectName("line_24")
        self.line_22 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_22.setGeometry(QtCore.QRect(570, 390, 156, 16))
        self.line_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setObjectName("line_22")
        self.line_64 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_64.setGeometry(QtCore.QRect(810, 540, 21, 21))
        self.line_64.setStyleSheet("")
        self.line_64.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_64.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_64.setObjectName("line_64")
        self.line_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_16.setGeometry(QtCore.QRect(770, 190, 20, 31))
        self.line_16.setStyleSheet("")
        self.line_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setObjectName("line_16")
        self.line_49 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_49.setGeometry(QtCore.QRect(850, 510, 21, 21))
        self.line_49.setStyleSheet("")
        self.line_49.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setObjectName("line_49")
        self.line_51 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_51.setGeometry(QtCore.QRect(720, 540, 21, 21))
        self.line_51.setStyleSheet("")
        self.line_51.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setObjectName("line_51")
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setGeometry(QtCore.QRect(680, 530, 21, 16))
        self.label_24.setObjectName("label_24")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label.setObjectName("label")
        self.plain_lineEdit_S2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S2.setEnabled(False)
        self.plain_lineEdit_S2.setGeometry(QtCore.QRect(630, 560, 41, 21))
        self.plain_lineEdit_S2.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S2.setObjectName("plain_lineEdit_S2")
        self.comboBox_key = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_key.setGeometry(QtCore.QRect(70, 22, 71, 21))
        self.comboBox_key.setObjectName("comboBox_key")
        self.comboBox_key.addItem("")
        self.comboBox_key.addItem("")
        self.comboBox_plain = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_plain.setGeometry(QtCore.QRect(510, 22, 71, 21))
        self.comboBox_plain.setObjectName("comboBox_plain")
        self.comboBox_plain.addItem("")
        self.comboBox_plain.addItem("")
        self.plain_lineEdit_bin = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_bin.setEnabled(False)
        self.plain_lineEdit_bin.setGeometry(QtCore.QRect(470, 100, 401, 21))
        self.plain_lineEdit_bin.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_bin.setObjectName("plain_lineEdit_bin")
        self.line_21 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_21.setGeometry(QtCore.QRect(560, 180, 221, 21))
        self.line_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setObjectName("line_21")
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setGeometry(QtCore.QRect(110, 190, 20, 31))
        self.line_6.setStyleSheet("")
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setObjectName("line_6")
        self.line_23 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_23.setGeometry(QtCore.QRect(660, 40, 20, 61))
        self.line_23.setStyleSheet("")
        self.line_23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setObjectName("line_23")
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setGeometry(QtCore.QRect(330, 280, 20, 21))
        self.line_11.setStyleSheet("")
        self.line_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setObjectName("line_11")
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setGeometry(QtCore.QRect(640, 530, 21, 16))
        self.label_23.setObjectName("label_23")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(240, 200, 21, 16))
        self.label_6.setObjectName("label_6")
        self.line_32 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_32.setGeometry(QtCore.QRect(740, 411, 31, 20))
        self.line_32.setStyleSheet("")
        self.line_32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setObjectName("line_32")
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setGeometry(QtCore.QRect(770, 530, 21, 16))
        self.label_26.setObjectName("label_26")
        self.line_40 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_40.setGeometry(QtCore.QRect(810, 470, 21, 21))
        self.line_40.setStyleSheet("")
        self.line_40.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setObjectName("line_40")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(630, 150, 81, 16))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(750, 260, 60, 16))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.line_34 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_34.setGeometry(QtCore.QRect(600, 470, 21, 21))
        self.line_34.setStyleSheet("")
        self.line_34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setObjectName("line_34")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setGeometry(QtCore.QRect(600, 530, 21, 16))
        self.label_22.setObjectName("label_22")
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setGeometry(QtCore.QRect(810, 530, 21, 16))
        self.label_28.setObjectName("label_28")
        self.key_lineEdit_C1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_lineEdit_C1.setEnabled(False)
        self.key_lineEdit_C1.setGeometry(QtCore.QRect(16, 300, 209, 21))
        self.key_lineEdit_C1.setFont(font28)
        self.key_lineEdit_C1.setAlignment(QtCore.Qt.AlignCenter)
        self.key_lineEdit_C1.setObjectName("key_lineEdit_C1")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(200, 150, 60, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setGeometry(QtCore.QRect(330, 240, 20, 21))
        self.line_9.setStyleSheet("")
        self.line_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setGeometry(QtCore.QRect(330, 190, 20, 31))
        self.line_7.setStyleSheet("")
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setGeometry(QtCore.QRect(110, 240, 20, 21))
        self.line_8.setStyleSheet("")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setObjectName("line_8")
        self.line_33 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_33.setGeometry(QtCore.QRect(740, 450, 31, 21))
        self.line_33.setStyleSheet("")
        self.line_33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_33.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_33.setObjectName("line_33")
        self.line_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_17.setGeometry(QtCore.QRect(550, 190, 20, 31))
        self.line_17.setStyleSheet("")
        self.line_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setObjectName("line_17")
        self.plain_lineEdit_B1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B1.setEnabled(False)
        self.plain_lineEdit_B1.setGeometry(QtCore.QRect(590, 490, 41, 21))
        self.plain_lineEdit_B1.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B1.setObjectName("plain_lineEdit_B1")
        self.line_67 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_67.setGeometry(QtCore.QRect(740, 596, 31, 20))
        self.line_67.setStyleSheet("")
        self.line_67.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_67.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_67.setObjectName("line_67")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(460, 200, 21, 16))
        self.label_12.setObjectName("label_12")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 21, 16))
        self.label_5.setObjectName("label_5")
        self.plain_lineEdit_S4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S4.setEnabled(False)
        self.plain_lineEdit_S4.setGeometry(QtCore.QRect(710, 560, 41, 21))
        self.plain_lineEdit_S4.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S4.setObjectName("plain_lineEdit_S4")
        self.plain_lineEdit_S3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S3.setEnabled(False)
        self.plain_lineEdit_S3.setGeometry(QtCore.QRect(670, 560, 41, 21))
        self.plain_lineEdit_S3.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S3.setObjectName("plain_lineEdit_S3")
        self.line_37 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_37.setGeometry(QtCore.QRect(640, 540, 21, 21))
        self.line_37.setStyleSheet("")
        self.line_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setObjectName("line_37")
        self.line_31 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_31.setGeometry(QtCore.QRect(740, 371, 31, 20))
        self.line_31.setStyleSheet("")
        self.line_31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setObjectName("line_31")
        self.line_66 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_66.setGeometry(QtCore.QRect(610, 586, 291, 20))
        self.line_66.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_66.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_66.setObjectName("line_66")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(190, 60, 60, 16))
        self.label_3.setObjectName("label_3")
        self.plain_lineEdit_B8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B8.setEnabled(False)
        self.plain_lineEdit_B8.setGeometry(QtCore.QRect(880, 490, 41, 21))
        self.plain_lineEdit_B8.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B8.setObjectName("plain_lineEdit_B8")
        self.line_14 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_14.setGeometry(QtCore.QRect(439, 10, 21, 1111))
        self.line_14.setStyleSheet("")
        self.line_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setObjectName("line_14")
        self.plain_lineEdit_B6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B6.setEnabled(False)
        self.plain_lineEdit_B6.setGeometry(QtCore.QRect(800, 490, 41, 21))
        self.plain_lineEdit_B6.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B6.setObjectName("plain_lineEdit_B6")
        self.line_65 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_65.setGeometry(QtCore.QRect(850, 580, 21, 16))
        self.line_65.setStyleSheet("")
        self.line_65.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_65.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_65.setObjectName("line_65")
        self.key_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_lineEdit.setGeometry(QtCore.QRect(160, 20, 141, 21))
        self.key_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.key_lineEdit.setObjectName("key_lineEdit")
        self.line_27 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_27.setGeometry(QtCore.QRect(530, 0, 401, 20))
        self.line_27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setObjectName("line_27")
        self.key_lineEdit_D0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_lineEdit_D0.setEnabled(False)
        self.key_lineEdit_D0.setGeometry(QtCore.QRect(236, 220, 209, 21))
        self.key_lineEdit_D0.setFont(font28)
        self.key_lineEdit_D0.setAlignment(QtCore.Qt.AlignCenter)
        self.key_lineEdit_D0.setObjectName("key_lineEdit_D0")
        self.plain_lineEdit_B2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B2.setEnabled(False)
        self.plain_lineEdit_B2.setGeometry(QtCore.QRect(630, 490, 41, 21))
        self.plain_lineEdit_B2.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B2.setObjectName("plain_lineEdit_B2")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setGeometry(QtCore.QRect(720, 640, 71, 31))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.line_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_12.setGeometry(QtCore.QRect(110, 320, 21, 21))
        self.line_12.setStyleSheet("")
        self.line_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setObjectName("line_12")
        self.plain_lineEdit_S8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S8.setEnabled(False)
        self.plain_lineEdit_S8.setGeometry(QtCore.QRect(880, 560, 41, 21))
        self.plain_lineEdit_S8.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S8.setObjectName("plain_lineEdit_S8")
        self.line_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_18.setGeometry(QtCore.QRect(560, 320, 20, 79))
        self.line_18.setStyleSheet("")
        self.line_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setObjectName("line_18")
        self.line_45 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_45.setGeometry(QtCore.QRect(680, 510, 21, 21))
        self.line_45.setStyleSheet("")
        self.line_45.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setObjectName("line_45")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(460, 0, 101, 16))
        self.label_14.setObjectName("label_14")
        self.line_48 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_48.setGeometry(QtCore.QRect(770, 510, 21, 21))
        self.line_48.setStyleSheet("")
        self.line_48.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setObjectName("line_48")
        self.line_53 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_53.setGeometry(QtCore.QRect(890, 580, 21, 16))
        self.line_53.setStyleSheet("")
        self.line_53.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_53.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_53.setObjectName("line_53")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 31, 21))
        self.label_2.setObjectName("label_2")
        self.plain_lineEdit_B4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B4.setEnabled(False)
        self.plain_lineEdit_B4.setGeometry(QtCore.QRect(710, 490, 41, 21))
        self.plain_lineEdit_B4.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B4.setObjectName("plain_lineEdit_B4")
        self.plain_lineEdit_S5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S5.setEnabled(False)
        self.plain_lineEdit_S5.setGeometry(QtCore.QRect(760, 560, 41, 21))
        self.plain_lineEdit_S5.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S5.setObjectName("plain_lineEdit_S5")
        self.line_62 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_62.setGeometry(QtCore.QRect(600, 580, 21, 16))
        self.line_62.setStyleSheet("")
        self.line_62.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_62.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_62.setObjectName("line_62")
        self.line_25 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_25.setGeometry(QtCore.QRect(770, 280, 20, 21))
        self.line_25.setStyleSheet("")
        self.line_25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setObjectName("line_25")
        self.plain_lineEdit_B7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B7.setEnabled(False)
        self.plain_lineEdit_B7.setGeometry(QtCore.QRect(840, 490, 41, 21))
        self.plain_lineEdit_B7.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B7.setObjectName("plain_lineEdit_B7")
        self.line_26 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_26.setGeometry(QtCore.QRect(920, 10, 21, 1111))
        self.line_26.setStyleSheet("")
        self.line_26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setObjectName("line_26")
        self.line_56 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_56.setGeometry(QtCore.QRect(720, 580, 21, 16))
        self.line_56.setStyleSheet("")
        self.line_56.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_56.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_56.setObjectName("line_56")
        self.line_58 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_58.setGeometry(QtCore.QRect(770, 580, 21, 16))
        self.line_58.setStyleSheet("")
        self.line_58.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_58.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_58.setObjectName("line_58")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(720, 389, 71, 21))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(90, 260, 60, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.line_46 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_46.setGeometry(QtCore.QRect(720, 510, 21, 21))
        self.line_46.setStyleSheet("")
        self.line_46.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setObjectName("line_46")
        self.line_60 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_60.setGeometry(QtCore.QRect(600, 540, 21, 21))
        self.line_60.setStyleSheet("")
        self.line_60.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_60.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_60.setObjectName("line_60")
        self.key_lineEdit_C0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_lineEdit_C0.setEnabled(False)
        self.key_lineEdit_C0.setGeometry(QtCore.QRect(16, 220, 209, 21))
        self.key_lineEdit_C0.setFont(font28)
        self.key_lineEdit_C0.setAlignment(QtCore.Qt.AlignCenter)
        self.key_lineEdit_C0.setObjectName("key_lineEdit_C0")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(475, 20, 31, 21))
        self.label_13.setObjectName("label_13")
        self.key_lineEdit_K1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_lineEdit_K1.setEnabled(False)
        self.key_lineEdit_K1.setGeometry(QtCore.QRect(590, 350, 331, 21))
        self.key_lineEdit_K1.setFont(font56)
        self.key_lineEdit_K1.setAlignment(QtCore.Qt.AlignCenter)
        self.key_lineEdit_K1.setObjectName("key_lineEdit_K1")
        self.key_lineEdit_D1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_lineEdit_D1.setEnabled(False)
        self.key_lineEdit_D1.setGeometry(QtCore.QRect(236, 300, 209, 21))
        self.key_lineEdit_D1.setFont(font28)
        self.key_lineEdit_D1.setAlignment(QtCore.Qt.AlignCenter)
        self.key_lineEdit_D1.setObjectName("key_lineEdit_D1")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setGeometry(QtCore.QRect(120, 0, 331, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.line_35 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_35.setGeometry(QtCore.QRect(640, 470, 21, 21))
        self.line_35.setStyleSheet("")
        self.line_35.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setObjectName("line_35")
        self.line_30 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_30.setGeometry(QtCore.QRect(660, 170, 20, 21))
        self.line_30.setStyleSheet("")
        self.line_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setObjectName("line_30")
        self.plain_lineEdit_xor_ER_K1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_xor_ER_K1.setEnabled(False)
        self.plain_lineEdit_xor_ER_K1.setGeometry(QtCore.QRect(630, 430, 251, 21))
        self.plain_lineEdit_xor_ER_K1.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_xor_ER_K1.setObjectName("plain_lineEdit_xor_ER_K1")
        self.line_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_20.setGeometry(QtCore.QRect(450, 20, 16, 1101))
        self.line_20.setStyleSheet("")
        self.line_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setObjectName("line_20")
        self.line_38 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_38.setGeometry(QtCore.QRect(720, 470, 21, 21))
        self.line_38.setStyleSheet("")
        self.line_38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setObjectName("line_38")
        self.line_36 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_36.setGeometry(QtCore.QRect(680, 470, 21, 21))
        self.line_36.setStyleSheet("")
        self.line_36.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setObjectName("line_36")
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_10.setGeometry(QtCore.QRect(110, 280, 20, 21))
        self.line_10.setStyleSheet("")
        self.line_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setObjectName("line_10")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(240, 280, 21, 16))
        self.label_10.setObjectName("label_10")
        self.line_47 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_47.setGeometry(QtCore.QRect(890, 510, 21, 21))
        self.line_47.setStyleSheet("")
        self.line_47.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setObjectName("line_47")
        self.plain_lineEdit_R0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_R0.setEnabled(False)
        self.plain_lineEdit_R0.setGeometry(QtCore.QRect(680, 220, 201, 21))
        self.plain_lineEdit_R0.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_R0.setObjectName("plain_lineEdit_R0")
        self.line_29 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_29.setGeometry(QtCore.QRect(550, 240, 20, 481))
        self.line_29.setStyleSheet("")
        self.line_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setObjectName("line_29")
        self.line_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_19.setGeometry(QtCore.QRect(770, 240, 20, 21))
        self.line_19.setStyleSheet("")
        self.line_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setObjectName("line_19")
        self.line_63 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_63.setGeometry(QtCore.QRect(810, 580, 21, 16))
        self.line_63.setStyleSheet("")
        self.line_63.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_63.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_63.setObjectName("line_63")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setGeometry(QtCore.QRect(630, 60, 60, 16))
        self.label_17.setObjectName("label_17")
        self.line_39 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_39.setGeometry(QtCore.QRect(770, 470, 21, 21))
        self.line_39.setStyleSheet("")
        self.line_39.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_39.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_39.setObjectName("line_39")
        self.line_41 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_41.setGeometry(QtCore.QRect(890, 470, 21, 21))
        self.line_41.setStyleSheet("")
        self.line_41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_41.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_41.setObjectName("line_41")
        self.plain_lineEdit_B3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B3.setEnabled(False)
        self.plain_lineEdit_B3.setGeometry(QtCore.QRect(670, 490, 41, 21))
        self.plain_lineEdit_B3.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B3.setObjectName("plain_lineEdit_B3")
        self.plain_lineEdit_S1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S1.setEnabled(False)
        self.plain_lineEdit_S1.setGeometry(QtCore.QRect(590, 560, 41, 21))
        self.plain_lineEdit_S1.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S1.setObjectName("plain_lineEdit_S1")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(20, 280, 21, 16))
        self.label_9.setObjectName("label_9")
        self.line_42 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_42.setGeometry(QtCore.QRect(850, 470, 21, 21))
        self.line_42.setStyleSheet("")
        self.line_42.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setObjectName("line_42")
        self.plain_lineEdit_B5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_B5.setEnabled(False)
        self.plain_lineEdit_B5.setGeometry(QtCore.QRect(760, 490, 41, 21))
        self.plain_lineEdit_B5.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_B5.setObjectName("plain_lineEdit_B5")
        self.line_57 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_57.setGeometry(QtCore.QRect(680, 580, 21, 16))
        self.line_57.setStyleSheet("")
        self.line_57.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_57.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_57.setObjectName("line_57")
        self.line_68 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_68.setGeometry(QtCore.QRect(740, 630, 31, 16))
        self.line_68.setStyleSheet("")
        self.line_68.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_68.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_68.setObjectName("line_68")
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setGeometry(QtCore.QRect(120, 180, 221, 21))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.line_59 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_59.setGeometry(QtCore.QRect(640, 580, 21, 16))
        self.line_59.setStyleSheet("")
        self.line_59.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_59.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_59.setObjectName("line_59")
        self.plain_lineEdit_S6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S6.setEnabled(False)
        self.plain_lineEdit_S6.setGeometry(QtCore.QRect(800, 560, 41, 21))
        self.plain_lineEdit_S6.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S6.setObjectName("plain_lineEdit_S6")
        self.line_61 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_61.setGeometry(QtCore.QRect(680, 540, 21, 21))
        self.line_61.setStyleSheet("")
        self.line_61.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_61.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_61.setObjectName("line_61")
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(220, 170, 20, 21))
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.plain_lineEdit_L0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_L0.setEnabled(False)
        self.plain_lineEdit_L0.setGeometry(QtCore.QRect(460, 220, 201, 21))
        self.plain_lineEdit_L0.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_L0.setObjectName("plain_lineEdit_L0")
        self.line_43 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_43.setGeometry(QtCore.QRect(600, 510, 21, 21))
        self.line_43.setStyleSheet("")
        self.line_43.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setObjectName("line_43")
        self.plain_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit.setGeometry(QtCore.QRect(600, 20, 141, 21))
        self.plain_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit.setObjectName("plain_lineEdit")
        self.line_52 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_52.setGeometry(QtCore.QRect(890, 540, 21, 21))
        self.line_52.setStyleSheet("")
        self.line_52.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_52.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_52.setObjectName("line_52")
        self.line_50 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_50.setGeometry(QtCore.QRect(810, 510, 21, 21))
        self.line_50.setStyleSheet("")
        self.line_50.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setObjectName("line_50")
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setGeometry(QtCore.QRect(850, 530, 21, 16))
        self.label_27.setObjectName("label_27")
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(220, 120, 20, 31))
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setGeometry(QtCore.QRect(890, 530, 21, 16))
        self.label_29.setObjectName("label_29")
        self.key_lineEdit_bin = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_lineEdit_bin.setEnabled(False)
        self.key_lineEdit_bin.setGeometry(QtCore.QRect(15, 100, 431, 21))
        self.key_lineEdit_bin.setFont(font64)
        self.key_lineEdit_bin.setAlignment(QtCore.Qt.AlignCenter)
        self.key_lineEdit_bin.setObjectName("key_lineEdit_bin")
        self.line_13 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_13.setGeometry(QtCore.QRect(330, 320, 20, 21))
        self.line_13.setStyleSheet("")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setObjectName("line_13")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(310, 260, 60, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(220, 40, 20, 61))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setGeometry(QtCore.QRect(860, 330, 21, 16))
        self.label_21.setObjectName("label_21")
        self.plain_lineEdit_S7_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_S7_22.setEnabled(False)
        self.plain_lineEdit_S7_22.setGeometry(QtCore.QRect(840, 560, 41, 21))
        self.plain_lineEdit_S7_22.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_S7_22.setObjectName("plain_lineEdit_S7_22")
        self.plain_lineEdit_E_R = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_E_R.setEnabled(False)
        self.plain_lineEdit_E_R.setGeometry(QtCore.QRect(565, 300, 331, 21))
        self.plain_lineEdit_E_R.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_E_R.setObjectName("plain_lineEdit_E_R")
        self.zip = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.zip.setEnabled(False)
        self.zip.setGeometry(QtCore.QRect(660, 610, 191, 21))
        self.zip.setAlignment(QtCore.Qt.AlignCenter)
        self.zip.setObjectName("zip")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setGeometry(QtCore.QRect(680, 200, 21, 16))
        self.label_20.setObjectName("label_20")
        self.line_15 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_15.setGeometry(QtCore.QRect(0, 20, 21, 1101))
        self.line_15.setStyleSheet("")
        self.line_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setObjectName("line_15")
        self.line_44 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_44.setGeometry(QtCore.QRect(640, 510, 21, 21))
        self.line_44.setStyleSheet("")
        self.line_44.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setObjectName("line_44")
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setGeometry(QtCore.QRect(720, 530, 21, 16))
        self.label_25.setObjectName("label_25")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setGeometry(QtCore.QRect(200, 350, 60, 21))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.line_69 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_69.setGeometry(QtCore.QRect(120, 330, 221, 21))
        self.line_69.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_69.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_69.setObjectName("line_69")
        self.line_70 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_70.setGeometry(QtCore.QRect(220, 340, 20, 16))
        self.line_70.setStyleSheet("")
        self.line_70.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_70.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_70.setObjectName("line_70")
        self.line_71 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_71.setGeometry(QtCore.QRect(260, 350, 330, 21))
        self.line_71.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_71.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_71.setObjectName("line_71")
        self.p = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.p.setEnabled(False)
        self.p.setGeometry(QtCore.QRect(660, 680, 191, 21))
        self.p.setAlignment(QtCore.Qt.AlignCenter)
        self.p.setObjectName("p")
        self.line_72 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_72.setGeometry(QtCore.QRect(740, 660, 31, 21))
        self.line_72.setStyleSheet("")
        self.line_72.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_72.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_72.setObjectName("line_72")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_30.setGeometry(QtCore.QRect(720, 710, 71, 21))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.line_73 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_73.setGeometry(QtCore.QRect(740, 729, 31, 21))
        self.line_73.setStyleSheet("")
        self.line_73.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_73.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_73.setObjectName("line_73")
        self.line_74 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_74.setGeometry(QtCore.QRect(740, 700, 31, 16))
        self.line_74.setStyleSheet("")
        self.line_74.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_74.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_74.setObjectName("line_74")
        self.plain_lineEdit_R1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_R1.setEnabled(False)
        self.plain_lineEdit_R1.setGeometry(QtCore.QRect(660, 750, 191, 21))
        self.plain_lineEdit_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_R1.setObjectName("plain_lineEdit_R1")
        self.line_75 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_75.setGeometry(QtCore.QRect(560, 710, 171, 21))
        self.line_75.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_75.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_75.setObjectName("line_75")
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_31.setGeometry(QtCore.QRect(660, 730, 21, 16))
        self.label_31.setObjectName("label_31")
        self.plain_lineEdit_L1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_L1.setEnabled(False)
        self.plain_lineEdit_L1.setGeometry(QtCore.QRect(460, 750, 191, 21))
        self.plain_lineEdit_L1.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_L1.setObjectName("plain_lineEdit_L1")
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_32.setGeometry(QtCore.QRect(460, 730, 41, 16))
        self.label_32.setObjectName("label_32")
        self.line_76 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_76.setGeometry(QtCore.QRect(110, 346, 20, 16))
        self.line_76.setStyleSheet("")
        self.line_76.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_76.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_76.setObjectName("line_76")
        self.line_77 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_77.setGeometry(QtCore.QRect(110, 370, 20, 16))
        self.line_77.setStyleSheet("")
        self.line_77.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_77.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_77.setObjectName("line_77")
        self.line_78 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_78.setGeometry(QtCore.QRect(110, 396, 20, 16))
        self.line_78.setStyleSheet("")
        self.line_78.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_78.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_78.setObjectName("line_78")
        self.line_79 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_79.setGeometry(QtCore.QRect(110, 420, 20, 16))
        self.line_79.setStyleSheet("")
        self.line_79.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_79.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_79.setObjectName("line_79")
        self.line_80 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_80.setGeometry(QtCore.QRect(330, 346, 20, 16))
        self.line_80.setStyleSheet("")
        self.line_80.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_80.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_80.setObjectName("line_80")
        self.line_81 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_81.setGeometry(QtCore.QRect(330, 370, 20, 16))
        self.line_81.setStyleSheet("")
        self.line_81.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_81.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_81.setObjectName("line_81")
        self.line_82 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_82.setGeometry(QtCore.QRect(330, 420, 20, 16))
        self.line_82.setStyleSheet("")
        self.line_82.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_82.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_82.setObjectName("line_82")
        self.line_83 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_83.setGeometry(QtCore.QRect(330, 396, 20, 16))
        self.line_83.setStyleSheet("")
        self.line_83.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_83.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_83.setObjectName("line_83")
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_65.setGeometry(QtCore.QRect(90, 450, 60, 21))
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_66.setGeometry(QtCore.QRect(310, 450, 60, 21))
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.line_167 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_167.setGeometry(QtCore.QRect(110, 480, 20, 16))
        self.line_167.setStyleSheet("")
        self.line_167.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_167.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_167.setObjectName("line_167")
        self.line_168 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_168.setGeometry(QtCore.QRect(110, 504, 20, 16))
        self.line_168.setStyleSheet("")
        self.line_168.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_168.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_168.setObjectName("line_168")
        self.line_169 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_169.setGeometry(QtCore.QRect(110, 554, 20, 16))
        self.line_169.setStyleSheet("")
        self.line_169.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_169.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_169.setObjectName("line_169")
        self.line_170 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_170.setGeometry(QtCore.QRect(110, 530, 20, 16))
        self.line_170.setStyleSheet("")
        self.line_170.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_170.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_170.setObjectName("line_170")
        self.line_171 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_171.setGeometry(QtCore.QRect(330, 480, 20, 16))
        self.line_171.setStyleSheet("")
        self.line_171.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_171.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_171.setObjectName("line_171")
        self.line_172 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_172.setGeometry(QtCore.QRect(330, 504, 20, 16))
        self.line_172.setStyleSheet("")
        self.line_172.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_172.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_172.setObjectName("line_172")
        self.line_173 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_173.setGeometry(QtCore.QRect(330, 554, 20, 16))
        self.line_173.setStyleSheet("")
        self.line_173.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_173.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_173.setObjectName("line_173")
        self.line_174 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_174.setGeometry(QtCore.QRect(330, 530, 20, 16))
        self.line_174.setStyleSheet("")
        self.line_174.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_174.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_174.setObjectName("line_174")
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_67.setGeometry(QtCore.QRect(110, 590, 21, 16))
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_68.setGeometry(QtCore.QRect(330, 590, 21, 16))
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.line_266 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_266.setGeometry(QtCore.QRect(110, 676, 20, 16))
        self.line_266.setStyleSheet("")
        self.line_266.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_266.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_266.setObjectName("line_266")
        self.line_267 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_267.setGeometry(QtCore.QRect(110, 626, 20, 16))
        self.line_267.setStyleSheet("")
        self.line_267.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_267.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_267.setObjectName("line_267")
        self.line_268 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_268.setGeometry(QtCore.QRect(110, 700, 20, 16))
        self.line_268.setStyleSheet("")
        self.line_268.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_268.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_268.setObjectName("line_268")
        self.line_269 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_269.setGeometry(QtCore.QRect(110, 650, 20, 16))
        self.line_269.setStyleSheet("")
        self.line_269.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_269.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_269.setObjectName("line_269")
        self.line_270 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_270.setGeometry(QtCore.QRect(330, 676, 20, 16))
        self.line_270.setStyleSheet("")
        self.line_270.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_270.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_270.setObjectName("line_270")
        self.line_271 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_271.setGeometry(QtCore.QRect(330, 626, 20, 16))
        self.line_271.setStyleSheet("")
        self.line_271.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_271.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_271.setObjectName("line_271")
        self.line_272 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_272.setGeometry(QtCore.QRect(330, 700, 20, 16))
        self.line_272.setStyleSheet("")
        self.line_272.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_272.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_272.setObjectName("line_272")
        self.line_273 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_273.setGeometry(QtCore.QRect(330, 650, 20, 16))
        self.line_273.setStyleSheet("")
        self.line_273.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_273.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_273.setObjectName("line_273")
        self.label_105 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_105.setGeometry(QtCore.QRect(480, 340, 21, 16))
        self.label_105.setObjectName("label_105")
        self.line_282 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_282.setGeometry(QtCore.QRect(750, 771, 20, 21))
        self.line_282.setStyleSheet("")
        self.line_282.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_282.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_282.setObjectName("line_282")
        self.line_283 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_283.setGeometry(QtCore.QRect(750, 800, 20, 16))
        self.line_283.setStyleSheet("")
        self.line_283.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_283.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_283.setObjectName("line_283")
        self.line_284 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_284.setGeometry(QtCore.QRect(750, 826, 20, 16))
        self.line_284.setStyleSheet("")
        self.line_284.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_284.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_284.setObjectName("line_284")
        self.line_285 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_285.setGeometry(QtCore.QRect(750, 850, 20, 16))
        self.line_285.setStyleSheet("")
        self.line_285.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_285.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_285.setObjectName("line_285")
        self.line_306 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_306.setGeometry(QtCore.QRect(550, 826, 20, 16))
        self.line_306.setStyleSheet("")
        self.line_306.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_306.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_306.setObjectName("line_306")
        self.line_307 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_307.setGeometry(QtCore.QRect(550, 771, 20, 21))
        self.line_307.setStyleSheet("")
        self.line_307.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_307.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_307.setObjectName("line_307")
        self.line_308 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_308.setGeometry(QtCore.QRect(550, 800, 20, 16))
        self.line_308.setStyleSheet("")
        self.line_308.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_308.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_308.setObjectName("line_308")
        self.line_309 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_309.setGeometry(QtCore.QRect(550, 850, 20, 16))
        self.line_309.setStyleSheet("")
        self.line_309.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_309.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_309.setObjectName("line_309")
        self.label_112 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_112.setGeometry(QtCore.QRect(550, 870, 21, 16))
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.label_113 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_113.setGeometry(QtCore.QRect(750, 870, 21, 16))
        self.label_113.setAlignment(QtCore.Qt.AlignCenter)
        self.label_113.setObjectName("label_113")
        self.line_310 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_310.setGeometry(QtCore.QRect(550, 959, 20, 16))
        self.line_310.setStyleSheet("")
        self.line_310.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_310.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_310.setObjectName("line_310")
        self.line_311 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_311.setGeometry(QtCore.QRect(550, 935, 20, 16))
        self.line_311.setStyleSheet("")
        self.line_311.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_311.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_311.setObjectName("line_311")
        self.line_312 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_312.setGeometry(QtCore.QRect(550, 909, 20, 16))
        self.line_312.setStyleSheet("")
        self.line_312.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_312.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_312.setObjectName("line_312")
        self.line_313 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_313.setGeometry(QtCore.QRect(550, 881, 20, 20))
        self.line_313.setStyleSheet("")
        self.line_313.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_313.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_313.setObjectName("line_313")
        self.line_314 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_314.setGeometry(QtCore.QRect(750, 959, 20, 16))
        self.line_314.setStyleSheet("")
        self.line_314.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_314.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_314.setObjectName("line_314")
        self.line_315 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_315.setGeometry(QtCore.QRect(750, 935, 20, 16))
        self.line_315.setStyleSheet("")
        self.line_315.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_315.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_315.setObjectName("line_315")
        self.line_316 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_316.setGeometry(QtCore.QRect(750, 909, 20, 16))
        self.line_316.setStyleSheet("")
        self.line_316.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_316.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_316.setObjectName("line_316")
        self.line_317 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_317.setGeometry(QtCore.QRect(750, 881, 20, 20))
        self.line_317.setStyleSheet("")
        self.line_317.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_317.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_317.setObjectName("line_317")
        self.plain_lineEdit_R16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_R16.setEnabled(False)
        self.plain_lineEdit_R16.setGeometry(QtCore.QRect(660, 970, 191, 21))
        self.plain_lineEdit_R16.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_R16.setObjectName("plain_lineEdit_R16")
        self.plain_lineEdit_L16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_L16.setEnabled(False)
        self.plain_lineEdit_L16.setGeometry(QtCore.QRect(460, 970, 191, 21))
        self.plain_lineEdit_L16.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_L16.setObjectName("plain_lineEdit_L16")
        self.label_114 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_114.setGeometry(QtCore.QRect(460, 950, 41, 16))
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_115.setGeometry(QtCore.QRect(660, 950, 31, 16))
        self.label_115.setObjectName("label_115")
        self.line_549 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_549.setGeometry(QtCore.QRect(750, 990, 20, 21))
        self.line_549.setStyleSheet("")
        self.line_549.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_549.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_549.setObjectName("line_549")
        self.line_551 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_551.setGeometry(QtCore.QRect(560, 1000, 201, 21))
        self.line_551.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_551.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_551.setObjectName("line_551")
        self.line_550 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_550.setGeometry(QtCore.QRect(650, 1010, 20, 16))
        self.line_550.setStyleSheet("")
        self.line_550.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_550.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_550.setObjectName("line_550")
        self.line_548 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_548.setGeometry(QtCore.QRect(550, 990, 21, 21))
        self.line_548.setStyleSheet("")
        self.line_548.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_548.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_548.setObjectName("line_548")
        self.plain_lineEdit_R16L16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.plain_lineEdit_R16L16.setEnabled(False)
        self.plain_lineEdit_R16L16.setGeometry(QtCore.QRect(460, 1020, 401, 21))
        self.plain_lineEdit_R16L16.setAlignment(QtCore.Qt.AlignCenter)
        self.plain_lineEdit_R16L16.setObjectName("plain_lineEdit_R16L16")
        self.label_198 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_198.setGeometry(QtCore.QRect(460, 1000, 51, 16))
        self.label_198.setObjectName("label_198")
        self.line_552 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_552.setGeometry(QtCore.QRect(650, 1040, 20, 16))
        self.line_552.setStyleSheet("")
        self.line_552.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_552.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_552.setObjectName("line_552")
        self.label_199 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_199.setGeometry(QtCore.QRect(630, 1050, 61, 31))
        self.label_199.setAlignment(QtCore.Qt.AlignCenter)
        self.label_199.setObjectName("label_199")
        self.line_553 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_553.setGeometry(QtCore.QRect(650, 1070, 20, 16))
        self.line_553.setStyleSheet("")
        self.line_553.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_553.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_553.setObjectName("line_553")
        self.ciphertext = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ciphertext.setEnabled(False)
        self.ciphertext.setGeometry(QtCore.QRect(460, 1080, 401, 21))
        self.ciphertext.setAlignment(QtCore.Qt.AlignCenter)
        self.ciphertext.setObjectName("ciphertext")
        self.label_200 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_200.setGeometry(QtCore.QRect(460, 1060, 41, 16))
        self.label_200.setAlignment(QtCore.Qt.AlignCenter)
        self.label_200.setObjectName("label_200")
        self.line_554 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_554.setGeometry(QtCore.QRect(10, 1110, 921, 21))
        self.line_554.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_554.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_554.setObjectName("line_554")
        self.key_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.key_button.setGeometry(QtCore.QRect(310, 20, 91, 21))
        self.key_button.setObjectName("key_button")
        self.key_button_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.key_button_2.setGeometry(QtCore.QRect(760, 20, 51, 21))
        self.key_button_2.setObjectName("key_button_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.key_button.clicked.connect(self.Key)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_plain.setItemText(0, _translate("MainWindow", "ASCII"))
        self.comboBox_plain.setItemText(1, _translate("MainWindow", "HEX"))
        self.comboBox_key.setItemText(0, _translate("MainWindow", "ASCII"))
        self.comboBox_key.setItemText(1, _translate("MainWindow", "HEX"))
        self.label_24.setText(_translate("MainWindow", "S3"))
        self.label.setText(_translate("MainWindow", "1.子密钥产生过程"))
        self.label_23.setText(_translate("MainWindow", "S2"))
        self.label_6.setText(_translate("MainWindow", "D0"))
        self.label_26.setText(_translate("MainWindow", "S5"))
        self.label_16.setText(_translate("MainWindow", "初识置换IP"))
        self.label_11.setText(_translate("MainWindow", "扩展置换E"))
        self.label_22.setText(_translate("MainWindow", "S1"))
        self.label_28.setText(_translate("MainWindow", "S6"))
        self.label_4.setText(_translate("MainWindow", "等分密钥"))
        self.label_12.setText(_translate("MainWindow", "L0"))
        self.label_5.setText(_translate("MainWindow", "C0"))
        self.label_3.setText(_translate("MainWindow", "比特流"))
        self.label_18.setText(_translate("MainWindow", "置换P运算"))
        self.label_14.setText(_translate("MainWindow", "2.加密过程"))
        self.label_2.setText(_translate("MainWindow", "密钥"))
        self.label_15.setText(_translate("MainWindow", "异或运算"))
        self.label_7.setText(_translate("MainWindow", "循环左移"))
        self.label_13.setText(_translate("MainWindow", "明文"))
        self.label_10.setText(_translate("MainWindow", "D1"))
        self.label_17.setText(_translate("MainWindow", "比特流"))
        self.label_9.setText(_translate("MainWindow", "C1"))
        self.label_27.setText(_translate("MainWindow", "S7"))
        self.label_29.setText(_translate("MainWindow", "S8"))
        self.label_8.setText(_translate("MainWindow", "循环左移"))
        self.label_21.setText(_translate("MainWindow", "K1"))
        self.label_20.setText(_translate("MainWindow", "R0"))
        self.label_25.setText(_translate("MainWindow", "S4"))
        self.label_19.setText(_translate("MainWindow", "等分密钥"))
        self.label_30.setText(_translate("MainWindow", "异或运算"))
        self.label_31.setText(_translate("MainWindow", "R1"))
        self.label_32.setText(_translate("MainWindow", "L1=R0"))
        self.label_65.setText(_translate("MainWindow", "循环左移"))
        self.label_66.setText(_translate("MainWindow", "循环左移"))
        self.label_67.setText(_translate("MainWindow", "Ci"))
        self.label_68.setText(_translate("MainWindow", "Di"))
        self.label_105.setText(_translate("MainWindow", "K1"))
        self.label_112.setText(_translate("MainWindow", "Li"))
        self.label_113.setText(_translate("MainWindow", "Ri"))
        self.label_114.setText(_translate("MainWindow", "L16"))
        self.label_115.setText(_translate("MainWindow", "R16"))
        self.label_198.setText(_translate("MainWindow", "R16L16"))
        self.label_199.setText(_translate("MainWindow", "IP-1"))
        self.label_200.setText(_translate("MainWindow", "密文："))
        self.key_button.setText(_translate("MainWindow", "生成子密钥"))
        self.key_button_2.setText(_translate("MainWindow", "加密"))

    def Key(self):
        if self.comboBox_key.currentText()=='ASCII':
            print('当前选择输入的是ASCII字符')
            Ui_MainWindow.mydes.__set_charKey__(self.key_lineEdit.text())
            # print('成功拿到字符密钥', Ui_MainWindow.mydes.charKey)
            self.key_re_display()

        else:
            print('当前选择输入的是十六进制')
            Ui_MainWindow.mydes.__set_hexKey__(self.key_lineEdit.text())
            # print('成功拿到十六进制密钥',Ui_MainWindow.mydes.hexKey)
            self.key_re_display()

    def key_re_display(self):
        self.key_lineEdit_bin.setText(Ui_MainWindow.mydes.__get_binKey__())
        self.key_lineEdit_C0.setText(Ui_MainWindow.mydes.__get_C0__())
        self.key_lineEdit_D0.setText(Ui_MainWindow.mydes.__get_D0__())
        self.key_lineEdit_C1.setText(Ui_MainWindow.mydes.__get_C1__())
        self.key_lineEdit_D1.setText(Ui_MainWindow.mydes.__get_D1__())
        self.key_lineEdit_K1.setText(Ui_MainWindow.mydes.__get_K1__())

    def Plain(self):
        if self.comboBox_plain.currentText()=='ASCII':
            print('当前选择输入的是ASCII字符')
            # Ui_MainWindow.mydes.__set_charKey__(self.key_lineEdit.text())
            # print('成功拿到字符密钥', Ui_MainWindow.mydes.charKey)
            self.plain_re_display()

        else:
            print('当前选择输入的是十六进制')
            # Ui_MainWindow.mydes.__set_hexKey__(self.key_lineEdit.text())
            # print('成功拿到十六进制密钥',Ui_MainWindow.mydes.hexKey)
            self.plain_re_display()

    def plain_re_display(self):
        pass